### PR TITLE
Feature/demos and README

### PR DESCRIPTION
**Pull request by keerl**

### CODE REVIEW

**Comment by farfromrefug** [comment]
@keerl please don't add npm I to tsc script 
I use pnpm. You changes on this breaks it for me. Let s make it work for everyone and every dev flow.

Also don't add build angular to npm build script. It is separated on purpose to make build in dev faster.

**Comment by keerl** [comment]
@farfromrefug sorry, I'll remove the `npm i` from the setup script. Also, I didn't add the angular build to the npm build script, I just added that to the README under demos so people are aware the angular build is different.

**Comment by farfromrefug** [comment]
About angular sorry I saw it on the other repo. Collectionview i think?
Sorry for that !

**Comment by keerl** [comment]
I don't see it in collection view either, that does sound vaguely familiar though. If you can find it, I will fix it. Sorry for the issues.

**Pull request merged**
